In [357]:
import numpy as np
import matplotlib as p
import os
import pandas as pd
import re
import string
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import linalg
from pandas import *

In [358]:
def RidgeAnalytical(x,y,L):
    x=np.matrix(x)
    y=np.matrix(y).transpose()
    XTX = x.transpose()*x
    XTY = x.transpose()*y
    LI = L*np.matrix(np.identity(len(XTX)))
    LI[0,0]=0
    beta = linalg.inv(XTX-LI)*XTY
    y_hat = np.dot(x,beta)
    residuals = y_hat - y
    SSE = residuals.transpose()*residuals
    MSE = SSE/len(X)
    print "the parameter estimates are:"
    print beta
    print "the mean squared error is:" , MSE

In [303]:
os.chdir('/Users/shani16/ds')
os.getcwd() 
os.system('mkdir today')

256

In [304]:
books = pd.read_csv('/Users/shani16/ds/data/book.csv', index_col=0, skipinitialspace=True)
movies = pd.read_csv('/Users/shani16/ds/data/movies.csv', index_col=0)

In [305]:
def remove_punctuation(s):
    s = ''.join([i for i in s if i not in frozenset(string.punctuation)])
    return s

In [306]:
movies['title1']=movies['title'].str.replace(r"\(.*\)","")
books['title1']=books['book'].str.replace(r"\(.*\)","")
movies['title1'] = movies['title1'].apply(remove_punctuation)
books['title1'] = books['title1'].apply(remove_punctuation)
books['title1'] =books['title1'].replace({'The': ""}, regex=True)
movies['title1']= movies['title1'].replace({'The': ""}, regex=True)
books['title1']= books['title1'].str.lower()
movies['title1']= movies['title1'].str.lower()
movies.title1 = pd.Series(movies.title1).str.replace(' ','')
books.title1 = pd.Series(books.title1).str.replace(' ','')

In [307]:
test= pd.merge(books, movies, on='title1')
unmatch= books[(~books.title1.isin(test.title1))]

In [308]:
len(test)

602

In [309]:
test.drop(test.columns[[3, 5, 6]], axis=1, inplace=True)

In [310]:
test['runtime']=test['runtime'].str.replace(r"[","")
test['runtime']=test['runtime'].str.replace(r"]","")

In [311]:
test['runtime']=test.runtime.apply(str)

In [312]:



test['minute']= test['runtime'].str.extract("(\d+) min")

In [313]:
test['hr']= test['runtime'].str.extract("(\d)")

In [314]:
test['hr']=test.hr.apply(float)

In [315]:
test['hr']=test['hr']*60

In [316]:
test['minute']=test.minute.apply(float)

In [317]:
test['rtime']= test['hr']+test['minute']

In [318]:
test.head()

,book,movie,author,bestsell_author,genre,release_date,distributor,runtime,rating,budget,domestic_gross,comic_book,minute,hr,rtime
0,All the Pretty Horses,All the Pretty Horses,Cormac McCarthy,False,Western,2000-12-25 00:00:00,Miramax,"'1 ', ' 57 min.'",PG-13,$57 million,15540353,False,57,60,117
1,American Psycho,American Psycho,Bret Easton Ellis,False,Thriller,2000-04-14 00:00:00,Lions Gate,"'1 ', ' 44 min.'",R,$7 million,15070285,False,44,60,104
2,Animal Factory,"Animal Factory, The",Edward Bunker,False,Unknown,2000-10-20 00:00:00,Silver Nitrate,"'1 ', ' 34 min.'",R,NaN,43805,False,34,60,94
3,Battlefield Earth,Battlefield Earth,L. Ron Hubbard,False,Sci-Fi Adventure,2000-05-12 00:00:00,Warner Bros.,"'1 ', ' 57 min.'",PG-13,$73 million,21471685,False,57,60,117
4,"Beach, The","Beach, The",Alex Garland,False,Drama / Thriller,2000-02-11 00:00:00,Fox,"'1 ', ' 59 min.'",R,$50 million,39785027,False,59,60,119

In [320]:
test.drop(test.columns[[7]], axis=1, inplace=True)

In [321]:
test.columns

Index([u'book', u'movie', u'author', u'bestsell_author', u'genre',
       u'release_date', u'distributor', u'rating', u'budget',
       u'domestic_gross', u'comic_book', u'minute', u'hr', u'rtime'],
      dtype='object')

In [322]:
test.drop(test.columns[[11, 12]], axis=1, inplace=True)

In [323]:
test.head()

,book,movie,author,bestsell_author,genre,release_date,distributor,rating,budget,domestic_gross,comic_book,rtime
0,All the Pretty Horses,All the Pretty Horses,Cormac McCarthy,False,Western,2000-12-25 00:00:00,Miramax,PG-13,$57 million,15540353,False,117
1,American Psycho,American Psycho,Bret Easton Ellis,False,Thriller,2000-04-14 00:00:00,Lions Gate,R,$7 million,15070285,False,104
2,Animal Factory,"Animal Factory, The",Edward Bunker,False,Unknown,2000-10-20 00:00:00,Silver Nitrate,R,NaN,43805,False,94
3,Battlefield Earth,Battlefield Earth,L. Ron Hubbard,False,Sci-Fi Adventure,2000-05-12 00:00:00,Warner Bros.,PG-13,$73 million,21471685,False,117
4,"Beach, The","Beach, The",Alex Garland,False,Drama / Thriller,2000-02-11 00:00:00,Fox,R,$50 million,39785027,False,119

In [324]:
test['budget1']=test['budget'].str.extract("(\d+) million")

In [325]:
test['budget1']=test.budget1.apply(float)

In [326]:
test['budget2']= test['budget1']*1000000

In [327]:
len(test)

602

In [328]:
test.columns

Index([u'book', u'movie', u'author', u'bestsell_author', u'genre',
       u'release_date', u'distributor', u'rating', u'budget',
       u'domestic_gross', u'comic_book', u'rtime', u'budget1', u'budget2'],
      dtype='object')

In [329]:
test.drop(test.columns[[8, 12]], axis=1, inplace=True)

In [330]:
test.head()

,book,movie,author,bestsell_author,genre,release_date,distributor,rating,domestic_gross,comic_book,rtime,budget2
0,All the Pretty Horses,All the Pretty Horses,Cormac McCarthy,False,Western,2000-12-25 00:00:00,Miramax,PG-13,15540353,False,117,57000000
1,American Psycho,American Psycho,Bret Easton Ellis,False,Thriller,2000-04-14 00:00:00,Lions Gate,R,15070285,False,104,7000000
2,Animal Factory,"Animal Factory, The",Edward Bunker,False,Unknown,2000-10-20 00:00:00,Silver Nitrate,R,43805,False,94,NaN
3,Battlefield Earth,Battlefield Earth,L. Ron Hubbard,False,Sci-Fi Adventure,2000-05-12 00:00:00,Warner Bros.,PG-13,21471685,False,117,73000000
4,"Beach, The","Beach, The",Alex Garland,False,Drama / Thriller,2000-02-11 00:00:00,Fox,R,39785027,False,119,50000000

In [331]:
import pandas as pd
url = 'http://www.the-numbers.com/market/distributors'
dfs = pd.read_html(url, header=0)
dfs=dfs[0]

In [332]:
dfs=dfs.rename(columns = {'Distributor':'distributor'})
dfs=dfs.rename(columns = {'Total Box Office':'dis_bo'})

In [333]:
test1= pd.merge(dfs, test, on='distributor', how='right')

In [334]:
test1.columns

Index([           u'Rank',     u'distributor',          u'Movies',
                u'dis_bo',         u'Tickets',           u'Share',
                  u'book',           u'movie',          u'author',
       u'bestsell_author',           u'genre',    u'release_date',
                u'rating',  u'domestic_gross',      u'comic_book',
                 u'rtime',         u'budget2'],
      dtype='object')

In [336]:
test1.columns

Index([           u'Rank',     u'distributor',          u'Movies',
                u'dis_bo',         u'Tickets',           u'Share',
                  u'book',           u'movie',          u'author',
       u'bestsell_author',           u'genre',    u'release_date',
                u'rating',  u'domestic_gross',      u'comic_book',
                 u'rtime',         u'budget2'],
      dtype='object')

In [337]:
foo = lambda x: pd.Series([i for i in (x.split('/'))])
foo1 = lambda x: pd.Series([i for i in (x.split(' '))])
rev = test1['genre'].apply(foo)
rev.columns=["genre1", "delete"]
rev1 = rev['genre1'].apply(foo1)
rev1.columns=["genre1", "delete"]
rev1=rev1[['genre1']]

In [338]:
test1= pd.concat([test1, rev1], axis=1)

In [339]:
test1.head()

,Rank,distributor,Movies,dis_bo,Tickets,Share,book,movie,author,bestsell_author,genre,release_date,rating,domestic_gross,comic_book,rtime,budget2,genre1
0,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Battlefield Earth,Battlefield Earth,L. Ron Hubbard,False,Sci-Fi Adventure,2000-05-12 00:00:00,PG-13,21471685,False,117,73000000,Sci-Fi
1,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Get Carter,Jack's Return Home,Ted Lewis,False,Action,2000-10-06 00:00:00,R,14967182,False,102,6000000,Action
2,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,My Dog Skip,My Dog Skip,Willie Morris,False,Family,2000-01-14 00:00:00,PG,34134641,False,95,6000000,Family
3,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Pay It Forward,Pay It Forward,Catherine Ryan Hyde,False,Drama,2000-10-20 00:00:00,PG-13,33519628,False,123,40000000,Drama
4,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,"Perfect Storm, The",Perfect Storm: A True Story of Men Against the...,Sebastian Junger,False,Action Drama,2000-06-30 00:00:00,PG-13,182618434,False,129,140000000,Action

In [340]:
#test1.drop(test1.columns[[4,5,6]], axis=1, inplace=True)

In [341]:
test1.columns

Index([           u'Rank',     u'distributor',          u'Movies',
                u'dis_bo',         u'Tickets',           u'Share',
                  u'book',           u'movie',          u'author',
       u'bestsell_author',           u'genre',    u'release_date',
                u'rating',  u'domestic_gross',      u'comic_book',
                 u'rtime',         u'budget2',          u'genre1'],
      dtype='object')

In [342]:
test2=test1[["bestsell_author", "rating", "domestic_gross", "comic_book", "rtime", "budget2", "genre1"]]

In [343]:
genre=pd.get_dummies(test1['genre1'])

In [344]:
genre.columns

Index([u'Action', u'Adventure', u'Animation', u'Comedy', u'Crime',
       u'Documentary', u'Drama', u'Family', u'Fantasy', u'Foreign',
       u'Historical', u'Horror', u'IMAX', u'Music', u'Period', u'Romance',
       u'Romantic', u'Sci-Fi', u'Sports', u'Thriller', u'Unknown', u'War',
       u'Western'],
      dtype='object')

In [345]:

#test1['rating']=test1['rating'].str.replace(r"PG","PG-13")

In [346]:
rating=pd.get_dummies(test1['rating'])

In [347]:
df_new= pd.concat([test1, genre ,rating], axis=1)

In [348]:
calender[df]

Index([           u'Rank',     u'distributor',          u'Movies',
                u'dis_bo',         u'Tickets',           u'Share',
                  u'book',           u'movie',          u'author',
       u'bestsell_author',           u'genre',    u'release_date',
                u'rating',  u'domestic_gross',      u'comic_book',
                 u'rtime',         u'budget2',          u'genre1',
                u'Action',       u'Adventure',       u'Animation',
                u'Comedy',           u'Crime',     u'Documentary',
                 u'Drama',          u'Family',         u'Fantasy',
               u'Foreign',      u'Historical',          u'Horror',
                  u'IMAX',           u'Music',          u'Period',
               u'Romance',        u'Romantic',          u'Sci-Fi',
                u'Sports',        u'Thriller',         u'Unknown',
                   u'War',         u'Western',               u'G',
                 u'NC-17',              u'PG',           u'PG-13',
                     u'R',         u'Unknown',         u'Unrated'],
      dtype='object')

In [349]:
df_new['release_date']=pd.to_datetime(df_new['release_date'])

In [350]:
df_new['release_month']=df_new['release_date'].dt.month
df_new['release_year']=df_new['release_date'].dt.year
df_new['release_day']=df_new['release_date'].dt.day

In [351]:
df_new

,Rank,distributor,Movies,dis_bo,Tickets,Share,book,movie,author,bestsell_author,...,G,NC-17,PG,PG-13,R,Unknown,Unrated,release_month,release_year,release_day
0,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Battlefield Earth,Battlefield Earth,L. Ron Hubbard,False,...,0,0,0,1,0,0,0,5,2000,12
1,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Get Carter,Jack's Return Home,Ted Lewis,False,...,0,0,0,0,1,0,0,10,2000,6
2,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,My Dog Skip,My Dog Skip,Willie Morris,False,...,0,0,1,0,0,0,0,1,2000,14
3,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Pay It Forward,Pay It Forward,Catherine Ryan Hyde,False,...,0,0,0,1,0,0,0,10,2000,20
4,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,"Perfect Storm, The",Perfect Storm: A True Story of Men Against the...,Sebastian Junger,False,...,0,0,0,1,0,0,0,6,2000,30
5,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Charlotte Gray,Charlotte Gray,Sebastian Faulks,False,...,0,0,0,1,0,0,0,12,2001,28
6,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Exit Wounds,Exit Wounds,John Westermann,False,...,0,0,0,0,1,0,0,3,2001,16
7,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Harry Potter and the Sorcerer's Stone,Harry Potter and the Sorcerer's Stone,J. K. Rowling,True,...,0,0,1,0,0,0,0,11,2001,16
8,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Hearts in Atlantis,Hearts in Atlantis,Stephen King,True,...,0,0,0,1,0,0,0,9,2001,28
9,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Lord of the Rings: The Fellowship of the Ring,Lord of the Rings: The Fellowship of the Ring,J. R. R. Tolkien,True,...,0,0,0,1,0,0,0,6,2011,14
10,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,"Pledge, The","Pledge, The",Friedrich D?rrenmatt,False,...,0,0,0,0,1,0,0,1,2001,19
11,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Valentine,Valentine: A Novel,Tom Savage,False,...,0,0,0,0,1,0,0,2,2001,2
12,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Blood Work,Blood Work,Michael Connelly,False,...,0,0,0,0,1,0,0,8,2002,9
13,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Divine Secrets of the Ya-Ya Sisterhood,Divine Secrets of the Ya-Ya Sisterhood,Rebecca Wells,False,...,0,0,0,1,0,0,0,6,2002,7
14,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Harry Potter and the Chamber of Secrets,Harry Potter and the Chamber of Secrets,J. K. Rowling,True,...,0,0,1,0,0,0,0,11,2002,15
15,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Lord of the Rings: The Two Towers,Lord of the Rings: The Two Towers,J. R. R. Tolkien,True,...,0,0,0,1,0,0,0,6,2011,21
16,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Queen of the Damned,Queen of the Damned,Anne Rice,True,...,0,0,0,0,1,0,0,2,2002,22
17,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,White Oleander,White Oleander,Janet Fitch,False,...,0,0,0,1,0,0,0,10,2002,11
18,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Dreamcatcher,Dreamcatcher,Stephen King,True,...,0,0,0,0,1,0,0,3,2003,21
19,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Gods and Generals,Gods and Generals,Jeff Shaara,False,...,0,0,0,1,0,0,0,2,2003,21
20,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Lord of the Rings: The Return of the King,Lord of the Rings: The Return of the King,J. R. R. Tolkien,True,...,0,0,0,1,0,0,0,6,2011,28
21,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Matchstick Men,Matchstick Men,Eric Garcia,False,...,0,0,0,1,0,0,0,9,2003,12
22,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Mystic River,Mystic River,Dennis Lehane,False,...,0,0,0,0,1,0,0,10,2003,8
23,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,"Big Bounce, The","Big Bounce, The",Elmore Leonard,False,...,0,0,0,1,0,0,0,1,2004,30
24,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban,J. K. Rowling,True,...,0,0,1,0,0,0,0,6,2004,4
25,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Polar Express,Polar Express,Chris Van Allsburg,False,...,1,0,0,0,0,0,0,11,2004,10
26,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Polar Express,Polar Express,Chris Van Allsburg,False,...,1,0,0,0,0,0,0,11,2011,25
27,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Polar Express,Polar Express,Chris Van Allsburg,False,...,1,0,0,0,0,0,0,11,2012,21
28,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Polar Express,Polar Express,Chris Van Allsburg,False,...,1,0,0,0,0,0,0,11,2005,23
29,1,Warner Bros.,642,"$27,992,551,109",4273742225,14.89%,Polar Express,Polar Express,Chris Van Allsburg,False,...,1,0,0,0,0,0,0,11,2006,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,NaN,MGM (Weinstein),NaN,NaN,NaN,NaN,Hannibal Rising,Hannibal Rising (2006),Thomas Harris,False,...,0,0,0,0,1,0,0,2,2007,9
573,NaN,MGM (Weinstein),NaN,NaN,NaN,NaN,"Mist, The",Skeleton Crew,Stephen King,True,...,0,0,0,0,1,0,0,11,2007,21
574,NaN,MGM (Weinstein),NaN,NaN,NaN,NaN,"Nanny Diaries, The","Nanny Diaries, The",Emma Mclaughlin,False,...,0,0,0,1,0,0,0,8,2007,24
575,NaN,Columbia,NaN,NaN,NaN,NaN,3:10 to Yuma,Three-Ten to Yuma,Elmore Leonard,False,...,0,0,0,0,0,0,1,8,1957,7
576,NaN,Columbia,NaN,NaN,NaN,NaN,"Tempest, The",The Tempest,William Shakespeare,True,...,0,0,0,1,0,0,0,9,1982,3
577,NaN,Mountain Top Releasing,NaN,NaN,NaN,NaN,"List, The","List, The",Robert Whitlow,False,...,0,0,1,0,0,0,0,8,2007,10
578,NaN,Warner Bros. (New Line),NaN,NaN,NaN,NaN,Appaloosa,Appaloosa,Robert B. Parker,False,...,0,0,0,0,1,0,0,9,2008,19
579,NaN,Warner Bros. (New Line),NaN,NaN,NaN,NaN,He's Just Not That Into You,He's Just Not That Into You,Greg Behrendt,False,...,0,0,0,1,0,0,0,2,2009,6
580,NaN,Warner Bros. (New Line),NaN,NaN,NaN,NaN,Inkheart,Inkheart,Cornelia Funke,False,...,0,0,1,0,0,0,0,1,2009,23
581,NaN,Warner Bros. (New Line),NaN,NaN,NaN,NaN,My Sister's Keeper,My Sister's Keeper,Jodi Picoult,False,...,0,0,0,1,0,0,0,6,2009,26
582,NaN,Warner Bros. (New Line),NaN,NaN,NaN,NaN,"Time Traveler's Wife, The","Time Traveler's Wife, The",Audrey Niffenegger,False,...,0,0,0,1,0,0,0,8,2009,14
583,NaN,Warner Bros. (New Line),NaN,NaN,NaN,NaN,"Rite, The","Rite: The Making of a Modern Exorcist, The",Matt Baglio,False,...,0,0,0,1,0,0,0,1,2011,28
584,NaN,Warner Bros. (New Line),NaN,NaN,NaN,NaN,"Hobbit: An Unexpected Journey, The","Hobbit, The",J.R.R. Tolkien,False,...,0,0,0,1,0,0,0,12,2012,14
585,NaN,Senator Distribution,NaN,NaN,NaN,NaN,"Informers, The","Informers, The",Bret Easton Ellis,False,...,0,0,0,0,1,0,0,4,2009,24
586,NaN,Unknown,NaN,NaN,NaN,NaN,Iron Man,Iron Man,Stan Lee,False,...,0,0,0,0,0,0,1,7,2007,27
587,NaN,Peace Arch Entertainment,NaN,NaN,NaN,NaN,"Mysteries of Pittsburgh, The","Mysteries of Pittsburgh, The",Michael Chabon,False,...,0,0,0,0,1,0,0,4,2009,10
588,NaN,Peace Arch Entertainment,NaN,NaN,NaN,NaN,"Mysteries of Pittsburgh, The","Mysteries of Pittsburgh, The",Michael Chabon,False,...,0,0,0,0,1,0,0,4,2009,10
589,NaN,Eros,NaN,NaN,NaN,NaN,Wanted,Wanted,Mark Millar,False,...,0,0,0,0,0,0,1,9,2009,18
590,NaN,Screen Media,NaN,NaN,NaN,NaN,"Private Lives of Pippa Lee, The","Private Lives of Pippa Lee, The",Rebecca Miller,False,...,0,0,0,0,1,0,0,11,2009,27
591,NaN,Weinstein / Dimension,NaN,NaN,NaN,NaN,"Road, The","Road, The",Cormac McCarthy,False,...,0,0,0,0,1,0,0,11,2009,25
592,NaN,Weinstein / Dimension,NaN,NaN,NaN,NaN,Youth in Revolt,Youth in Revolt,C. D. Payne,False,...,0,0,0,0,1,0,0,1,2010,8
593,NaN,RKO,NaN,NaN,NaN,NaN,Alice in Wonderland,Alice's Adventures in Wonderland and Through t...,Lewis Carroll,True,...,0,0,0,0,0,0,1,7,1951,28
594,NaN,Four of a Kind,NaN,NaN,NaN,NaN,"Romantics, The","Romantics, The",Galt Niederhoffer,False,...,0,0,0,1,0,0,0,9,2010,10
595,NaN,Samuel Goldwyn,NaN,NaN,NaN,NaN,Bloodworth,Provinces of Night,William Gay,False,...,0,0,0,0,1,0,0,5,2011,20
596,NaN,Anchor Bay Films,NaN,NaN,NaN,NaN,Kill the Irishman,To Kill the Irishman: The War that Crippled th...,Rick Porrello,False,...,0,0,0,0,1,0,0,3,2011,11
597,NaN,Main Street Films,NaN,NaN,NaN,NaN,Great Expectations,Great Expectations,Charles Dickens,True,...,0,0,0,1,0,0,0,11,2013,8
598,NaN,Lionsgate/Summit,NaN,NaN,NaN,NaN,"Perks of Being a Wallflower, The","Perks of Being a Wallflower, The",Stephen Chbosky,False,...,0,0,0,1,0,0,0,9,2012,21
599,NaN,Lionsgate/Summit,NaN,NaN,NaN,NaN,Ender's Game,Ender's Game,Orson Scott Card,False,...,0,0,0,1,0,0,0,11,2013,1
600,NaN,Lionsgate/Summit,NaN,NaN,NaN,NaN,Warm Bodies,Warm Bodies,Isaac Marion,False,...,0,0,0,1,0,0,0,2,2013,1
601,NaN,Open Road Films,NaN,NaN,NaN,NaN,The Host,The Host,Stephenie Meyer,True,...,0,0,0,1,0,0,0,3,2013,29

In [352]:

df_new.loc[df_new.release_month==5, "season"] = "Summer"
df_new.loc[df_new.release_month==6, "season"] = "Summer"
df_new.loc[df_new.release_month==7, "season"] = "Summer"
df_new.loc[df_new.release_month==11, "season"] = "Holiday"
df_new.loc[df_new.release_month==12, "season"] = "Holiday"
df_new.loc[df_new.release_month==1, "season"] = "Winter"
df_new.loc[df_new.release_month==2, "season"] = "Winter"
df_new.loc[df_new.release_month==3, "season"] = "Spring"
df_new.loc[df_new.release_month==4, "season"] = "Spring"
df_new.loc[df_new.release_month==8, "season"] = "Fall"
df_new.loc[df_new.release_month==9, "season"] = "Fall"
df_new.loc[df_new.release_month==10, "season"] = "Fall"

In [353]:
season=pd.get_dummies(df_new['season'])

In [354]:
df_new1 = pd.concat([season, df_new], axis=1)

In [355]:
df_new1

,Fall,Holiday,Spring,Summer,Winter,Rank,distributor,Movies,dis_bo,Tickets,...,NC-17,PG,PG-13,R,Unknown,Unrated,release_month,release_year,release_day,season
0,0,0,0,1,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,5,2000,12,Summer
1,1,0,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,10,2000,6,Fall
2,0,0,0,0,1,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,1,0,0,0,0,1,2000,14,Winter
3,1,0,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,10,2000,20,Fall
4,0,0,0,1,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,6,2000,30,Summer
5,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,12,2001,28,Holiday
6,0,0,1,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,3,2001,16,Spring
7,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,1,0,0,0,0,11,2001,16,Holiday
8,1,0,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,9,2001,28,Fall
9,0,0,0,1,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,6,2011,14,Summer
10,0,0,0,0,1,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,1,2001,19,Winter
11,0,0,0,0,1,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,2,2001,2,Winter
12,1,0,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,8,2002,9,Fall
13,0,0,0,1,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,6,2002,7,Summer
14,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,1,0,0,0,0,11,2002,15,Holiday
15,0,0,0,1,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,6,2011,21,Summer
16,0,0,0,0,1,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,2,2002,22,Winter
17,1,0,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,10,2002,11,Fall
18,0,0,1,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,3,2003,21,Spring
19,0,0,0,0,1,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,2,2003,21,Winter
20,0,0,0,1,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,6,2011,28,Summer
21,1,0,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,9,2003,12,Fall
22,1,0,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,1,0,0,10,2003,8,Fall
23,0,0,0,0,1,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,1,0,0,0,1,2004,30,Winter
24,0,0,0,1,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,1,0,0,0,0,6,2004,4,Summer
25,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,0,0,0,11,2004,10,Holiday
26,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,0,0,0,11,2011,25,Holiday
27,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,0,0,0,11,2012,21,Holiday
28,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,0,0,0,11,2005,23,Holiday
29,0,1,0,0,0,1,Warner Bros.,642,"$27,992,551,109",4273742225,...,0,0,0,0,0,0,11,2006,17,Holiday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,0,0,0,0,1,NaN,MGM (Weinstein),NaN,NaN,NaN,...,0,0,0,1,0,0,2,2007,9,Winter
573,0,1,0,0,0,NaN,MGM (Weinstein),NaN,NaN,NaN,...,0,0,0,1,0,0,11,2007,21,Holiday
574,1,0,0,0,0,NaN,MGM (Weinstein),NaN,NaN,NaN,...,0,0,1,0,0,0,8,2007,24,Fall
575,1,0,0,0,0,NaN,Columbia,NaN,NaN,NaN,...,0,0,0,0,0,1,8,1957,7,Fall
576,1,0,0,0,0,NaN,Columbia,NaN,NaN,NaN,...,0,0,1,0,0,0,9,1982,3,Fall
577,1,0,0,0,0,NaN,Mountain Top Releasing,NaN,NaN,NaN,...,0,1,0,0,0,0,8,2007,10,Fall
578,1,0,0,0,0,NaN,Warner Bros. (New Line),NaN,NaN,NaN,...,0,0,0,1,0,0,9,2008,19,Fall
579,0,0,0,0,1,NaN,Warner Bros. (New Line),NaN,NaN,NaN,...,0,0,1,0,0,0,2,2009,6,Winter
580,0,0,0,0,1,NaN,Warner Bros. (New Line),NaN,NaN,NaN,...,0,1,0,0,0,0,1,2009,23,Winter
581,0,0,0,1,0,NaN,Warner Bros. (New Line),NaN,NaN,NaN,...,0,0,1,0,0,0,6,2009,26,Summer
582,1,0,0,0,0,NaN,Warner Bros. (New Line),NaN,NaN,NaN,...,0,0,1,0,0,0,8,2009,14,Fall
583,0,0,0,0,1,NaN,Warner Bros. (New Line),NaN,NaN,NaN,...,0,0,1,0,0,0,1,2011,28,Winter
584,0,1,0,0,0,NaN,Warner Bros. (New Line),NaN,NaN,NaN,...,0,0,1,0,0,0,12,2012,14,Holiday
585,0,0,1,0,0,NaN,Senator Distribution,NaN,NaN,NaN,...,0,0,0,1,0,0,4,2009,24,Spring
586,0,0,0,1,0,NaN,Unknown,NaN,NaN,NaN,...,0,0,0,0,0,1,7,2007,27,Summer
587,0,0,1,0,0,NaN,Peace Arch Entertainment,NaN,NaN,NaN,...,0,0,0,1,0,0,4,2009,10,Spring
588,0,0,1,0,0,NaN,Peace Arch Entertainment,NaN,NaN,NaN,...,0,0,0,1,0,0,4,2009,10,Spring
589,1,0,0,0,0,NaN,Eros,NaN,NaN,NaN,...,0,0,0,0,0,1,9,2009,18,Fall
590,0,1,0,0,0,NaN,Screen Media,NaN,NaN,NaN,...,0,0,0,1,0,0,11,2009,27,Holiday
591,0,1,0,0,0,NaN,Weinstein / Dimension,NaN,NaN,NaN,...,0,0,0,1,0,0,11,2009,25,Holiday
592,0,0,0,0,1,NaN,Weinstein / Dimension,NaN,NaN,NaN,...,0,0,0,1,0,0,1,2010,8,Winter
593,0,0,0,1,0,NaN,RKO,NaN,NaN,NaN,...,0,0,0,0,0,1,7,1951,28,Summer
594,1,0,0,0,0,NaN,Four of a Kind,NaN,NaN,NaN,...,0,0,1,0,0,0,9,2010,10,Fall
595,0,0,0,1,0,NaN,Samuel Goldwyn,NaN,NaN,NaN,...,0,0,0,1,0,0,5,2011,20,Summer
596,0,0,1,0,0,NaN,Anchor Bay Films,NaN,NaN,NaN,...,0,0,0,1,0,0,3,2011,11,Spring
597,0,1,0,0,0,NaN,Main Street Films,NaN,NaN,NaN,...,0,0,1,0,0,0,11,2013,8,Holiday
598,1,0,0,0,0,NaN,Lionsgate/Summit,NaN,NaN,NaN,...,0,0,1,0,0,0,9,2012,21,Fall
599,0,1,0,0,0,NaN,Lionsgate/Summit,NaN,NaN,NaN,...,0,0,1,0,0,0,11,2013,1,Holiday
600,0,0,0,0,1,NaN,Lionsgate/Summit,NaN,NaN,NaN,...,0,0,1,0,0,0,2,2013,1,Winter
601,0,0,1,0,0,NaN,Open Road Films,NaN,NaN,NaN,...,0,0,1,0,0,0,3,2013,29,Spring

In [356]:
df_new1.to_csv('/Users/shani16/ds/data/luther.csv', index_col = False)

In [301]:
df_new1.columns

Index([           u'Fall',         u'Holiday',          u'Spring',
                u'Summer',          u'Winter',            u'Rank',
           u'distributor',          u'Movies',          u'dis_bo',
               u'Tickets',           u'Share',            u'book',
                 u'movie',          u'author', u'bestsell_author',
                 u'genre',    u'release_date',          u'rating',
        u'domestic_gross',      u'comic_book',           u'rtime',
               u'budget2',          u'genre1',          u'Action',
             u'Adventure',       u'Animation',          u'Comedy',
                 u'Crime',     u'Documentary',           u'Drama',
                u'Family',         u'Fantasy',         u'Foreign',
            u'Historical',          u'Horror',            u'IMAX',
                 u'Music',          u'Period',         u'Romance',
              u'Romantic',          u'Sci-Fi',          u'Sports',
              u'Thriller',         u'Unknown',             u'War',
               u'Western',               u'G',           u'NC-17',
                    u'PG',           u'PG-13',         u'Unknown',
               u'Unrated',   u'release_month',    u'release_year',
           u'release_day',          u'season'],
      dtype='object')